[package]
name = "ab_versions"
version = "0.9.1"
authors = ["Carl J. Geib"]
edition = "2021"


[dependencies]
cfb = "0.8"
thiserror = "1.0.20"
rayon = "1.7"



[dev-dependencies]
sevenz-rust = "0.5"
tempfile = "3.1.0"
walkdir = "2"
nom = "7"
