[package]
name = "ab_version_lib"
version = "0.8.0"
authors = ["Carl J. Geib"]
edition = "2018"

[dependencies]
cfb = "0.8"
thiserror = "1.0.20"



[dev-dependencies]
sevenz-rust = "0.4.3"
tempfile = "3.1.0"
walkdir = "2"
nom = "7"